export const BUTTONS = {
  CANCEL: 'Cancelar',
  CONFIRM: 'Confirmar',
  CONTINUE: 'Continuar',
  TRY_AGAIN: 'Volver a intentar',
  REGISTER: 'Registrar',
  TICKET: 'Comprobante',
  SHARE: 'Compartir',
  DOWNLOAD: 'Descargar',
  LOGIN: 'Iniciar sesión',
  CLOSE: 'Cerrar',
  START: 'Comenzar',
  SEND: 'Enviar',
  ADD_NEW_SENDER: 'Agregar nuevo destinatario',
  SEARCH_CONTACT: 'Buscar contacto',
  READY: '¡Listo!',
  TRANSFER: 'Trasnferir',
  SHARE_PROOF: 'Compartir comprobante',
  ADD_FAVORITE: 'Agregar a favoritos',
  REMOVE_FAVORITE: 'Eliminar de favoritos',
  ACCEPT: 'Aceptar',
  LOGOUT_CONFIRM_TITLE: '¿Seguro que deseas cerrar tu sesión?',
  LOGOUT_CONFIRM: 'Sí, cerrar',
  UNDERSTAND: 'Entendido',
  CANCEL_CONFIRM: 'Sí, cancelar',
  NOT_CANCEL: 'No cancelar',
  FINISH: 'Finalizar',
};
